blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/toankhontech/react-native-ultra-carousel/discussions
    about: Ask questions and discuss ideas
